# This file was auto-generated by Fern from our API Definition.

import typing

GenerateContentRequestContentType = typing.Union[
    typing.Literal["blog_post", "social_twitter", "social_instagram", "weekly_digest"],
    typing.Any,
]
