# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class RecipeVideoRequest(UniversalBaseModel):
    """
    Request body for recipe video generation.
    """

    dish_name: str = pydantic.Field()
    """
    Name of the dish
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Additional context or specific shots desired
    """

    style: typing.Optional[str] = pydantic.Field(default=None)
    """
    Video style: cinematic, tutorial, social, lifestyle
    """

    duration_seconds: typing.Optional[int] = pydantic.Field(default=None)
    """
    Video length (4-8 seconds)
    """

    aspect_ratio: typing.Optional[str] = pydantic.Field(default=None)
    """
    Aspect ratio: 16:9 (landscape) or 9:16 (portrait)
    """

    timeout_seconds: typing.Optional[int] = pydantic.Field(default=None)
    """
    Max wait time in seconds
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
