# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class VoiceFoodQueryResponse(UniversalBaseModel):
    """
    Response from voice food query.
    """

    status: str = pydantic.Field()
    """
    Status: search_requested, response, or error
    """

    query: typing.Optional[str] = pydantic.Field(default=None)
    """
    Extracted search query (if search requested)
    """

    user_id: str = pydantic.Field()
    """
    User ID for context
    """

    response_text: typing.Optional[str] = pydantic.Field(default=None)
    """
    AI's text response
    """

    response_audio_base64: typing.Optional[str] = pydantic.Field(default=None)
    """
    AI's audio response (base64)
    """

    error: typing.Optional[str] = pydantic.Field(default=None)
    """
    Error message if status is error
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
