# This file was auto-generated by Fern from our API Definition.

import typing
from ..core.client_wrapper import SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.video_response import VideoResponse
from ..core.pydantic_utilities import parse_obj_as
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.http_validation_error import HttpValidationError
from json.decoder import JSONDecodeError
from ..core.api_error import ApiError
from ..errors.service_unavailable_error import ServiceUnavailableError
from ..core.client_wrapper import AsyncClientWrapper

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class VideoClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def generate_recipe_video_endpoint(
        self,
        *,
        dish_name: str,
        description: typing.Optional[str] = OMIT,
        style: typing.Optional[str] = OMIT,
        duration_seconds: typing.Optional[int] = OMIT,
        aspect_ratio: typing.Optional[str] = OMIT,
        timeout_seconds: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> VideoResponse:
        """
        Generate a short AI video for a dish or recipe using Veo 3.1.

        Creates appetizing video content for:
        - Food presentations
        - Recipe showcases
        - Social media content

        **Styles**:
        - `cinematic`: Shallow depth of field, warm lighting
        - `tutorial`: Overhead cooking view, step-by-step
        - `social`: Trendy, quick cuts, vibrant colors
        - `lifestyle`: Person enjoying meal, cozy atmosphere

        **Note**: Video generation takes 2-5 minutes.

        Parameters
        ----------
        dish_name : str
            Name of the dish

        description : typing.Optional[str]
            Additional context or specific shots desired

        style : typing.Optional[str]
            Video style: cinematic, tutorial, social, lifestyle

        duration_seconds : typing.Optional[int]
            Video length (4-8 seconds)

        aspect_ratio : typing.Optional[str]
            Aspect ratio: 16:9 (landscape) or 9:16 (portrait)

        timeout_seconds : typing.Optional[int]
            Max wait time in seconds

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VideoResponse
            Successful Response

        Examples
        --------
        from fcp import FoodContextProtocolApi

        client = FoodContextProtocolApi(
            authorization="YOUR_AUTHORIZATION",
            base_url="https://yourhost.com/path/to/api",
        )
        client.video.generate_recipe_video_endpoint(
            dish_name="dish_name",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "video/recipe",
            method="POST",
            json={
                "dish_name": dish_name,
                "description": description,
                "style": style,
                "duration_seconds": duration_seconds,
                "aspect_ratio": aspect_ratio,
                "timeout_seconds": timeout_seconds,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    VideoResponse,
                    parse_obj_as(
                        type_=VideoResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def generate_cooking_clip_endpoint(
        self,
        *,
        action: str,
        ingredients: typing.Optional[typing.Sequence[str]] = OMIT,
        duration_seconds: typing.Optional[int] = OMIT,
        timeout_seconds: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> VideoResponse:
        """
        Generate a short B-roll style cooking action clip.

        Creates clips of cooking actions like:
        - Chopping vegetables
        - Sautéing ingredients
        - Flipping pancakes
        - Plating dishes

        **Note**: Video generation takes 2-5 minutes.

        Parameters
        ----------
        action : str
            Cooking action (e.g., 'chopping vegetables')

        ingredients : typing.Optional[typing.Sequence[str]]
            Optional list of ingredients being used

        duration_seconds : typing.Optional[int]
            Video length (4-8 seconds)

        timeout_seconds : typing.Optional[int]
            Max wait time in seconds

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VideoResponse
            Successful Response

        Examples
        --------
        from fcp import FoodContextProtocolApi

        client = FoodContextProtocolApi(
            authorization="YOUR_AUTHORIZATION",
            base_url="https://yourhost.com/path/to/api",
        )
        client.video.generate_cooking_clip_endpoint(
            action="action",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "video/clip",
            method="POST",
            json={
                "action": action,
                "ingredients": ingredients,
                "duration_seconds": duration_seconds,
                "timeout_seconds": timeout_seconds,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    VideoResponse,
                    parse_obj_as(
                        type_=VideoResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def generate_recipe_video_raw(
        self,
        *,
        dish_name: str,
        description: typing.Optional[str] = OMIT,
        style: typing.Optional[str] = OMIT,
        duration_seconds: typing.Optional[int] = OMIT,
        aspect_ratio: typing.Optional[str] = OMIT,
        timeout_seconds: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[typing.Any]:
        """
        Generate a recipe video and return raw MP4 bytes.

        Parameters
        ----------
        dish_name : str
            Name of the dish

        description : typing.Optional[str]
            Additional context or specific shots desired

        style : typing.Optional[str]
            Video style: cinematic, tutorial, social, lifestyle

        duration_seconds : typing.Optional[int]
            Video length (4-8 seconds)

        aspect_ratio : typing.Optional[str]
            Aspect ratio: 16:9 (landscape) or 9:16 (portrait)

        timeout_seconds : typing.Optional[int]
            Max wait time in seconds

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        from fcp import FoodContextProtocolApi

        client = FoodContextProtocolApi(
            authorization="YOUR_AUTHORIZATION",
            base_url="https://yourhost.com/path/to/api",
        )
        client.video.generate_recipe_video_raw(
            dish_name="dish_name",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "video/recipe/raw",
            method="POST",
            json={
                "dish_name": dish_name,
                "description": description,
                "style": style,
                "duration_seconds": duration_seconds,
                "aspect_ratio": aspect_ratio,
                "timeout_seconds": timeout_seconds,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    typing.Optional[typing.Any],
                    parse_obj_as(
                        type_=typing.Optional[typing.Any],  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncVideoClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def generate_recipe_video_endpoint(
        self,
        *,
        dish_name: str,
        description: typing.Optional[str] = OMIT,
        style: typing.Optional[str] = OMIT,
        duration_seconds: typing.Optional[int] = OMIT,
        aspect_ratio: typing.Optional[str] = OMIT,
        timeout_seconds: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> VideoResponse:
        """
        Generate a short AI video for a dish or recipe using Veo 3.1.

        Creates appetizing video content for:
        - Food presentations
        - Recipe showcases
        - Social media content

        **Styles**:
        - `cinematic`: Shallow depth of field, warm lighting
        - `tutorial`: Overhead cooking view, step-by-step
        - `social`: Trendy, quick cuts, vibrant colors
        - `lifestyle`: Person enjoying meal, cozy atmosphere

        **Note**: Video generation takes 2-5 minutes.

        Parameters
        ----------
        dish_name : str
            Name of the dish

        description : typing.Optional[str]
            Additional context or specific shots desired

        style : typing.Optional[str]
            Video style: cinematic, tutorial, social, lifestyle

        duration_seconds : typing.Optional[int]
            Video length (4-8 seconds)

        aspect_ratio : typing.Optional[str]
            Aspect ratio: 16:9 (landscape) or 9:16 (portrait)

        timeout_seconds : typing.Optional[int]
            Max wait time in seconds

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VideoResponse
            Successful Response

        Examples
        --------
        import asyncio

        from fcp import AsyncFoodContextProtocolApi

        client = AsyncFoodContextProtocolApi(
            authorization="YOUR_AUTHORIZATION",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.video.generate_recipe_video_endpoint(
                dish_name="dish_name",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "video/recipe",
            method="POST",
            json={
                "dish_name": dish_name,
                "description": description,
                "style": style,
                "duration_seconds": duration_seconds,
                "aspect_ratio": aspect_ratio,
                "timeout_seconds": timeout_seconds,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    VideoResponse,
                    parse_obj_as(
                        type_=VideoResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def generate_cooking_clip_endpoint(
        self,
        *,
        action: str,
        ingredients: typing.Optional[typing.Sequence[str]] = OMIT,
        duration_seconds: typing.Optional[int] = OMIT,
        timeout_seconds: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> VideoResponse:
        """
        Generate a short B-roll style cooking action clip.

        Creates clips of cooking actions like:
        - Chopping vegetables
        - Sautéing ingredients
        - Flipping pancakes
        - Plating dishes

        **Note**: Video generation takes 2-5 minutes.

        Parameters
        ----------
        action : str
            Cooking action (e.g., 'chopping vegetables')

        ingredients : typing.Optional[typing.Sequence[str]]
            Optional list of ingredients being used

        duration_seconds : typing.Optional[int]
            Video length (4-8 seconds)

        timeout_seconds : typing.Optional[int]
            Max wait time in seconds

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VideoResponse
            Successful Response

        Examples
        --------
        import asyncio

        from fcp import AsyncFoodContextProtocolApi

        client = AsyncFoodContextProtocolApi(
            authorization="YOUR_AUTHORIZATION",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.video.generate_cooking_clip_endpoint(
                action="action",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "video/clip",
            method="POST",
            json={
                "action": action,
                "ingredients": ingredients,
                "duration_seconds": duration_seconds,
                "timeout_seconds": timeout_seconds,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    VideoResponse,
                    parse_obj_as(
                        type_=VideoResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def generate_recipe_video_raw(
        self,
        *,
        dish_name: str,
        description: typing.Optional[str] = OMIT,
        style: typing.Optional[str] = OMIT,
        duration_seconds: typing.Optional[int] = OMIT,
        aspect_ratio: typing.Optional[str] = OMIT,
        timeout_seconds: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[typing.Any]:
        """
        Generate a recipe video and return raw MP4 bytes.

        Parameters
        ----------
        dish_name : str
            Name of the dish

        description : typing.Optional[str]
            Additional context or specific shots desired

        style : typing.Optional[str]
            Video style: cinematic, tutorial, social, lifestyle

        duration_seconds : typing.Optional[int]
            Video length (4-8 seconds)

        aspect_ratio : typing.Optional[str]
            Aspect ratio: 16:9 (landscape) or 9:16 (portrait)

        timeout_seconds : typing.Optional[int]
            Max wait time in seconds

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        import asyncio

        from fcp import AsyncFoodContextProtocolApi

        client = AsyncFoodContextProtocolApi(
            authorization="YOUR_AUTHORIZATION",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.video.generate_recipe_video_raw(
                dish_name="dish_name",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "video/recipe/raw",
            method="POST",
            json={
                "dish_name": dish_name,
                "description": description,
                "style": style,
                "duration_seconds": duration_seconds,
                "aspect_ratio": aspect_ratio,
                "timeout_seconds": timeout_seconds,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    typing.Optional[typing.Any],
                    parse_obj_as(
                        type_=typing.Optional[typing.Any],  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
