# This file was auto-generated by Fern from our API Definition.

import typing
from ..core.client_wrapper import SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.voice_meal_log_response import VoiceMealLogResponse
from ..core.pydantic_utilities import parse_obj_as
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.http_validation_error import HttpValidationError
from json.decoder import JSONDecodeError
from ..core.api_error import ApiError
from ..types.voice_food_query_response import VoiceFoodQueryResponse
from ..core.client_wrapper import AsyncClientWrapper

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class VoiceClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def voice_meal_log_endpoint(
        self,
        *,
        audio_base64: str,
        mime_type: typing.Optional[str] = OMIT,
        sample_rate: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> VoiceMealLogResponse:
        """
        Process voice input to log a meal using the Gemini Live API.

        The AI assistant will:
        - Understand the spoken meal description
        - Ask clarifying questions if needed
        - Extract structured meal data when ready

        **Audio formats supported**:
        - `audio/pcm`: Raw PCM audio
        - `audio/webm`: WebM audio
        - `audio/wav`: WAV audio

        **Sample rates**: 8000-48000 Hz (16000 recommended)

        **Returns**:
        - `logged`: Meal was successfully extracted
        - `clarification_needed`: AI needs more information
        - `error`: Processing failed

        Parameters
        ----------
        audio_base64 : str
            Base64-encoded audio data

        mime_type : typing.Optional[str]
            Audio MIME type (audio/pcm, audio/webm, audio/wav)

        sample_rate : typing.Optional[int]
            Sample rate in Hz

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VoiceMealLogResponse
            Successful Response

        Examples
        --------
        from fcp import FoodContextProtocolApi

        client = FoodContextProtocolApi(
            authorization="YOUR_AUTHORIZATION",
            base_url="https://yourhost.com/path/to/api",
        )
        client.voice.voice_meal_log_endpoint(
            audio_base64="audio_base64",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "voice/meal",
            method="POST",
            json={
                "audio_base64": audio_base64,
                "mime_type": mime_type,
                "sample_rate": sample_rate,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    VoiceMealLogResponse,
                    parse_obj_as(
                        type_=VoiceMealLogResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def voice_food_query_endpoint(
        self,
        *,
        audio_base64: str,
        mime_type: typing.Optional[str] = OMIT,
        sample_rate: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> VoiceFoodQueryResponse:
        """
        Process a voice query about food history using the Gemini Live API.

        The AI assistant will:
        - Understand natural language food queries
        - Extract search parameters
        - Provide conversational responses

        **Example queries**:
        - "What did I eat last week?"
        - "Show me my lunch from Tuesday"
        - "Find all the pasta dishes I've had"

        **Returns**:
        - `search_requested`: A search query was extracted
        - `response`: General response (no search needed)
        - `error`: Processing failed

        Parameters
        ----------
        audio_base64 : str
            Base64-encoded audio data

        mime_type : typing.Optional[str]
            Audio MIME type (audio/pcm, audio/webm, audio/wav)

        sample_rate : typing.Optional[int]
            Sample rate in Hz

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VoiceFoodQueryResponse
            Successful Response

        Examples
        --------
        from fcp import FoodContextProtocolApi

        client = FoodContextProtocolApi(
            authorization="YOUR_AUTHORIZATION",
            base_url="https://yourhost.com/path/to/api",
        )
        client.voice.voice_food_query_endpoint(
            audio_base64="audio_base64",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "voice/query",
            method="POST",
            json={
                "audio_base64": audio_base64,
                "mime_type": mime_type,
                "sample_rate": sample_rate,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    VoiceFoodQueryResponse,
                    parse_obj_as(
                        type_=VoiceFoodQueryResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncVoiceClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def voice_meal_log_endpoint(
        self,
        *,
        audio_base64: str,
        mime_type: typing.Optional[str] = OMIT,
        sample_rate: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> VoiceMealLogResponse:
        """
        Process voice input to log a meal using the Gemini Live API.

        The AI assistant will:
        - Understand the spoken meal description
        - Ask clarifying questions if needed
        - Extract structured meal data when ready

        **Audio formats supported**:
        - `audio/pcm`: Raw PCM audio
        - `audio/webm`: WebM audio
        - `audio/wav`: WAV audio

        **Sample rates**: 8000-48000 Hz (16000 recommended)

        **Returns**:
        - `logged`: Meal was successfully extracted
        - `clarification_needed`: AI needs more information
        - `error`: Processing failed

        Parameters
        ----------
        audio_base64 : str
            Base64-encoded audio data

        mime_type : typing.Optional[str]
            Audio MIME type (audio/pcm, audio/webm, audio/wav)

        sample_rate : typing.Optional[int]
            Sample rate in Hz

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VoiceMealLogResponse
            Successful Response

        Examples
        --------
        import asyncio

        from fcp import AsyncFoodContextProtocolApi

        client = AsyncFoodContextProtocolApi(
            authorization="YOUR_AUTHORIZATION",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.voice.voice_meal_log_endpoint(
                audio_base64="audio_base64",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "voice/meal",
            method="POST",
            json={
                "audio_base64": audio_base64,
                "mime_type": mime_type,
                "sample_rate": sample_rate,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    VoiceMealLogResponse,
                    parse_obj_as(
                        type_=VoiceMealLogResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def voice_food_query_endpoint(
        self,
        *,
        audio_base64: str,
        mime_type: typing.Optional[str] = OMIT,
        sample_rate: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> VoiceFoodQueryResponse:
        """
        Process a voice query about food history using the Gemini Live API.

        The AI assistant will:
        - Understand natural language food queries
        - Extract search parameters
        - Provide conversational responses

        **Example queries**:
        - "What did I eat last week?"
        - "Show me my lunch from Tuesday"
        - "Find all the pasta dishes I've had"

        **Returns**:
        - `search_requested`: A search query was extracted
        - `response`: General response (no search needed)
        - `error`: Processing failed

        Parameters
        ----------
        audio_base64 : str
            Base64-encoded audio data

        mime_type : typing.Optional[str]
            Audio MIME type (audio/pcm, audio/webm, audio/wav)

        sample_rate : typing.Optional[int]
            Sample rate in Hz

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VoiceFoodQueryResponse
            Successful Response

        Examples
        --------
        import asyncio

        from fcp import AsyncFoodContextProtocolApi

        client = AsyncFoodContextProtocolApi(
            authorization="YOUR_AUTHORIZATION",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.voice.voice_food_query_endpoint(
                audio_base64="audio_base64",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "voice/query",
            method="POST",
            json={
                "audio_base64": audio_base64,
                "mime_type": mime_type,
                "sample_rate": sample_rate,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    VoiceFoodQueryResponse,
                    parse_obj_as(
                        type_=VoiceFoodQueryResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
