# This file was auto-generated by Fern from our API Definition.

import typing
from ..core.client_wrapper import SyncClientWrapper
from .types.nearby_food_request_food_type import NearbyFoodRequestFoodType
from ..core.request_options import RequestOptions
from ..core.pydantic_utilities import parse_obj_as
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.http_validation_error import HttpValidationError
from json.decoder import JSONDecodeError
from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class DiscoveryClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def post_nearby_food(
        self,
        *,
        latitude: typing.Optional[float] = OMIT,
        longitude: typing.Optional[float] = OMIT,
        location: typing.Optional[str] = OMIT,
        radius: typing.Optional[float] = OMIT,
        food_type: typing.Optional[NearbyFoodRequestFoodType] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Dict[str, typing.Optional[typing.Any]]:
        """
        Find nearby restaurants or cafes using Google Maps.

        Parameters
        ----------
        latitude : typing.Optional[float]
            Latitude in degrees

        longitude : typing.Optional[float]
            Longitude in degrees

        location : typing.Optional[str]
            City name or address (e.g., 'San Francisco, CA')

        radius : typing.Optional[float]
            Search radius in meters

        food_type : typing.Optional[NearbyFoodRequestFoodType]
            Type of food venue to search for

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Optional[typing.Any]]
            Successful Response

        Examples
        --------
        from fcp import FoodContextProtocolApi

        client = FoodContextProtocolApi(
            authorization="YOUR_AUTHORIZATION",
            base_url="https://yourhost.com/path/to/api",
        )
        client.discovery.post_nearby_food()
        """
        _response = self._client_wrapper.httpx_client.request(
            "discovery/nearby",
            method="POST",
            json={
                "latitude": latitude,
                "longitude": longitude,
                "location": location,
                "radius": radius,
                "food_type": food_type,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    typing.Dict[str, typing.Optional[typing.Any]],
                    parse_obj_as(
                        type_=typing.Dict[str, typing.Optional[typing.Any]],  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncDiscoveryClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def post_nearby_food(
        self,
        *,
        latitude: typing.Optional[float] = OMIT,
        longitude: typing.Optional[float] = OMIT,
        location: typing.Optional[str] = OMIT,
        radius: typing.Optional[float] = OMIT,
        food_type: typing.Optional[NearbyFoodRequestFoodType] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Dict[str, typing.Optional[typing.Any]]:
        """
        Find nearby restaurants or cafes using Google Maps.

        Parameters
        ----------
        latitude : typing.Optional[float]
            Latitude in degrees

        longitude : typing.Optional[float]
            Longitude in degrees

        location : typing.Optional[str]
            City name or address (e.g., 'San Francisco, CA')

        radius : typing.Optional[float]
            Search radius in meters

        food_type : typing.Optional[NearbyFoodRequestFoodType]
            Type of food venue to search for

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Optional[typing.Any]]
            Successful Response

        Examples
        --------
        import asyncio

        from fcp import AsyncFoodContextProtocolApi

        client = AsyncFoodContextProtocolApi(
            authorization="YOUR_AUTHORIZATION",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.discovery.post_nearby_food()


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "discovery/nearby",
            method="POST",
            json={
                "latitude": latitude,
                "longitude": longitude,
                "location": location,
                "radius": radius,
                "food_type": food_type,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    typing.Dict[str, typing.Optional[typing.Any]],
                    parse_obj_as(
                        type_=typing.Dict[str, typing.Optional[typing.Any]],  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
