# This file was auto-generated by Fern from our API Definition.

import typing

NearbyFoodRequestFoodType = typing.Union[
    typing.Literal["restaurant", "cafe", "bar", "bakery", "meal_delivery"], typing.Any
]
